// Embeds the AssemblyScript standard library into the compiler so `compileScript` never touches the
// filesystem. Runs before `tsup`; the generated module is gitignored.

import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = resolve(fileURLToPath(new URL(".", import.meta.url)), "..");
const sourcePath = resolve(packageRoot, "index.ts");
const targetPath = resolve(packageRoot, "compiler/stdlib-source.generated.ts");

const source = await readFile(sourcePath, "utf8");

const contents = [
  "// GENERATED by scripts/pack-stdlib.mjs — do not edit by hand.",
  "//",
  "// The standard library is a single self-contained AssemblyScript file, embedded here so the",
  "// compiler can resolve it without reading from disk.",
  "",
  `export const STDLIB_SOURCE = ${JSON.stringify(source)};`,
  "",
].join("\n");

await writeFile(targetPath, contents);

console.log(`Packed the ${source.length}-byte stdlib into ${targetPath}`);
